name: "Upload build artifacts"
description: "Upload build artifacts"

runs:
  using: "composite"
  steps:
    ## NXCACHE
    - name: tar artifacts
      run: |
        time tar czf dist.tar.gz dist
        time tar czf nxcache.tar.gz nxcache
      shell: bash
    - name: update NX cache folder
      uses: actions/upload-artifact@v3
      continue-on-error: true
      with:
        path: nxcache.tar.gz
        name: nxcache-${{ github.ref_name }}
    ## DIST
    - name: update Dist folder
      uses: actions/upload-artifact@v3
      continue-on-error: true
      with:
        path: dist.tar.gz
        name: dist-${{ github.ref_name }}
