storage: ./.verdaccio_test_env/test-storage

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

auth:
  auth-memory:
    users:
      test:
        name: test
        password: test

logs:
  - {type: stdout, format: pretty, level: trace}

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $anonymous
    proxy: npmjs
  '**':
    access: $all
    publish: $anonymous
    proxy: npmjs
