name: 'Setup'
description: 'Initialize cache, env var load'
inputs:
  enable-cache:
    description: 'enable caching'
    required: false
    type: boolean
    default: 'true'
  enable-node-modules-cache:
    description: 'enable caching for node modules'
    required: false
    type: boolean
    default: 'true'
  act:
    description: 'enable act debug'
    required: false
    type: boolean
    default: 'false'
runs:
  using: "composite"
  steps:
      - name: install NPM
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version-file: '.nvmrc'
          cache-dependency-path: package-lock.json
      - name: get latest tag sha
        id: tag-sha
        uses: Alfresco/alfresco-build-tools/.github/actions/git-latest-tag@a3d5beb67a8b8d96398435e01686a9a9185380ab # v8.18.0
      - name: load "NPM TAG"
        uses: ./.github/actions/set-npm-tag
      - name: before install script
        uses: ./.github/actions/before-install
        with:
          act: ${{ inputs.act }}
