name: 'Setup'
description: 'Initialize cache, env var load'
inputs:
  enable-node-modules-cache:
    description: 'enable caching for node modules'
    required: false
    type: boolean
    default: 'true'
  act:
    description: 'enable act debug'
    required: false
    type: boolean
    default: 'false'
outputs:
  npm-tag:
    description: 'NPM tag'
    value: ${{ steps.set-npm-tag.outputs.npm-tag }}
runs:
  using: "composite"
  steps:
      - name: install NPM
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: '.nvmrc'
          cache-dependency-path: package-lock.json
      - name: get latest tag sha
        id: tag-sha
        uses: Alfresco/alfresco-build-tools/.github/actions/git-latest-tag@2d8a74e98bfdcc78252004141137f6d14a03e175 # v10.4.0
# CACHE
      - name: Node Modules cache
        id: node-modules-cache
        if: ${{ inputs.enable-node-modules-cache == 'true' }}
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        env:
          cache-name: node-modules-cache
        with:
          path: |
            node_modules
          key: .npm-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node_modules-${{ runner.os }}-build-${{ env.cache-name }}-
            node_modules-${{ runner.os }}-build-
            node_modules-${{ runner.os }}-
      - name: load "NPM TAG"
        id: set-npm-tag
        uses: ./.github/actions/set-npm-tag
      - name: before install script
        uses: ./.github/actions/before-install
        with:
          act: ${{ inputs.act }}
