name: 'Setup'
description: 'Initialize cache, env var load'
inputs:
  enable-cache:
    description: 'enable caching'
    required: false
    type: boolean
    default: 'true'
  enable-node-modules-cache:
    description: 'enable caching for node modules'
    required: false
    type: boolean
    default: 'true'
  act:
    description: 'enable act debug'
    required: false
    type: boolean
    default: 'false'
runs:
  using: "composite"
  steps:
      - name: install NPM
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version-file: '.nvmrc'
          cache-dependency-path: package-lock.json
      - name: get latest tag sha
        id: tag-sha
        uses: Alfresco/alfresco-build-tools/.github/actions/git-latest-tag@2eaedaf6e9f5c28366cbeea22c371cdce6c9c7b3 # v5.17.0
# CACHE
      - name: Node Modules cache
        id: node-modules-cache
        if: ${{ inputs.enable-node-modules-cache == 'true' }}
        uses: actions/cache@ab5e6d0c87105b4c9c2047343972218f562e4319 # v4.0.1
        env:
          cache-name: node-modules-cache
        with:
          path: |
            node_modules
          key: .npm-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node_modules-${{ runner.os }}-build-${{ env.cache-name }}-
            node_modules-${{ runner.os }}-build-
            node_modules-${{ runner.os }}-
      - name: pip cache
        uses: actions/cache@ab5e6d0c87105b4c9c2047343972218f562e4319 # v4.0.1
        if: ${{ inputs.enable-cache == 'true' }}
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-
          restore-keys: |
            ${{ runner.os }}
      - name: load "NPM TAG"
        uses: ./.github/actions/set-npm-tag
      - name: before install script
        uses: ./.github/actions/before-install
        with:
          act: ${{ inputs.act }}
