name: 'Setup'
description: 'Initialize cache, env var load'
inputs:
  enable-cache:
    description: 'enable caching'
    required: false
    type: boolean
    default: 'true'
  enable-node-modules-cache:
    description: 'enable caching for node modules'
    required: false
    type: boolean
    default: 'true'
  act:
    description: 'enable act debug'
    required: false
    type: boolean
    default: 'false'
runs:
  using: "composite"
  steps:
      - name: get latest tag sha
        id: tag-sha
        uses: Alfresco/alfresco-build-tools/.github/actions/git-latest-tag@a3d5beb67a8b8d96398435e01686a9a9185380ab # v8.18.0
      - name: load "NPM TAG"
        uses: ./.github/actions/set-npm-tag
      - name: Cache node modules
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
           ${{ runner.os }}-node-modules-
      - name: Cache nx cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684
        with:
          path: nxcache
          key: ${{ runner.os }}-nxcache-${{ hashFiles('nx.json') }}
          restore-keys: |
            ${{ runner.os }}-nxcache-
      - name: before install script
        uses: ./.github/actions/before-install
        with:
          act: ${{ inputs.act }}
