repos:
  - repo: https://github.com/rhysd/actionlint
    rev: 914e7df21a07ef503a81201c76d2b11c789d3fca  # frozen: v1.7.12
    hooks:
      - id: actionlint
        exclude: '^\.github/workflows/.*\.lock\.yml$'
