sonar.organization=alfresco
sonar.projectKey=Alfresco_alfresco-ng2-components

sonar.sources=lib
sonar.tests=lib
sonar.inclusions=lib/**/src/**
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,**/*.mock.ts,**/mock/**,**/mocks/**,**/testing/**,**/stories/**

sonar.javascript.lcov.reportPaths=coverage/core/lcov.info,coverage/content-services/lcov.info,coverage/extensions/lcov.info,coverage/insights/lcov.info,coverage/process-services/lcov.info,coverage/process-services-cloud/lcov.info

sonar.sourceEncoding=UTF-8
