/*!
 * @license
 * Copyright 2019 Alfresco Software, Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import {
    ABOUT_API_FACTORY_TOKEN,
    ACTIONS_API_FACTORY_TOKEN,
    ACTIVITI_COMMENTS_API_FACTORY_TOKEN,
    ACTIVITI_CONTENT_API_FACTORY_TOKEN,
    ACTIVITI_GROUPS_API_FACTORY_TOKEN,
    ASPECTS_API_FACTORY_TOKEN,
    AUDIT_API_FACTORY_TOKEN,
    AUTHENTICATION_API_FACTORY_TOKEN,
    CHECKLISTS_API_FACTORY_TOKEN,
    CLASSES_API_FACTORY_TOKEN,
    COMMENTS_API_FACTORY_TOKEN,
    CONTENT_API_FACTORY_TOKEN,
    CUSTOM_MODEL_API_FACTORY_TOKEN,
    DISCOVERY_API_FACTORY_TOKEN,
    DOWNLOADS_API_FACTORY_TOKEN,
    FAVORITES_API_FACTORY_TOKEN,
    FILES_API_FACTORY_TOKEN,
    FORM_MODELS_API_FACTORY_TOKEN,
    GROUPS_API_FACTORY_TOKEN,
    INTEGRATION_ALFRESCO_ON_PREMISE_API_FACTORY_TOKEN,
    MODELS_API_FACTORY_TOKEN,
    MODEL_JSON_BPMN_API_FACTORY_TOKEN,
    NODES_API_FACTORY_TOKEN,
    PEOPLE_API_FACTORY_TOKEN,
    PROCESS_DEFINITIONS_API_FACTORY_TOKEN,
    PROCESS_INSTANCES_API_FACTORY_TOKEN,
    PROCESS_INSTANCE_VARIABLES_API_FACTORY_TOKEN,
    QUERIES_API_FACTORY_TOKEN,
    RATINGS_API_FACTORY_TOKEN,
    RECORDS_API_FACTORY_TOKEN,
    RENDITIONS_API_FACTORY_TOKEN,
    REPORT_API_FACTORY_TOKEN,
    RUNTIME_APP_DEFINITIONS_API_FACTORY_TOKEN,
    SCRIPT_FILES_API_FACTORY_TOKEN,
    SEARCH_API_FACTORY_TOKEN,
    SECURITY_GROUPS_API_FACTORY_TOKEN,
    SECURITY_MARKS_API_FACTORY_TOKEN,
    SHARED_LINKS_API_FACTORY_TOKEN,
    SITES_API_FACTORY_TOKEN,
    SYSTEM_PROPERTIES_API_FACTORY_TOKEN,
    TAGS_API_FACTORY_TOKEN,
    TASKS_API_FACTORY_TOKEN,
    TASK_ACTIONS_API_FACTORY_TOKEN,
    TASK_FORMS_API_FACTORY_TOKEN,
    TRASHCAN_API_FACTORY_TOKEN,
    TYPES_API_FACTORY_TOKEN,
    UPLOAD_API_FACTORY_TOKEN,
    USERS_API_FACTORY_TOKEN,
    USER_FILTERS_API_FACTORY_TOKEN,
    USER_PROFILE_API_FACTORY_TOKEN,
    VERSIONS_API_FACTORY_TOKEN,
    WEBSCRIPT_API_FACTORY_TOKEN
} from '../tokens';
import {
    AboutApiLegacyFactory,
    ActionsApiLegacyFactory,
    ActivitiCommentsApiLegacyFactory,
    ActivitiContentApiLegacyFactory,
    ActivitiGroupsApiLegacyFactory,
    AspectsApiLegacyFactory,
    AuditApiLegacyFactory,
    AuthenticationApiLegacyFactory,
    ChecklistsApiLegacyFactory,
    ClassesApiLegacyFactory,
    CommentsApiLegacyFactory,
    ContentApiLegacyFactory,
    CustomModelApiLegacyFactory,
    DiscoveryApiLegacyFactory,
    DownloadsApiLegacyFactory,
    FavoritesApiLegacyFactory,
    FilesApiLegacyFactory,
    FormModelsApiLegacyFactory,
    GroupsApiLegacyFactory,
    IntegrationAlfrescoOnPremiseApiLegacyFactory,
    ModelJsonBpmnApiLegacyFactory,
    ModelsApiLegacyFactory,
    NodesApiLegacyFactory,
    PeopleApiLegacyFactory,
    ProcessDefinitionsApiLegacyFactory,
    ProcessInstancesApiLegacyFactory,
    ProcessInstanceVariablesApiLegacyFactory,
    QueriesApiLegacyFactory,
    RatingsApiLegacyFactory,
    RecordsApiLegacyFactory,
    RenditionsApiLegacyFactory,
    ReportApiLegacyFactory,
    RuntimeAppDefinitionsApiLegacyFactory,
    ScriptFilesApiLegacyFactory,
    SearchApiLegacyFactory,
    SecurityGroupsApiLegacyFactory,
    SecurityMarksApiLegacyFactory,
    SharedLinksApiLegacyFactory,
    SitesApiLegacyFactory,
    SystemPropertiesApiLegacyFactory,
    TagsApiLegacyFactory,
    TaskActionsApiLegacyFactory,
    TaskFormsApiLegacyFactory,
    TasksApiLegacyFactory,
    TrashcanApiLegacyFactory,
    TypesApiLegacyFactory,
    UploadApiLegacyFactory,
    UserFiltersApiLegacyFactory,
    UserProfileApiLegacyFactory,
    UsersApiLegacyFactory,
    VersionsApiLegacyFactory,
    WebscriptApiLegacyFactory
} from './factories';

@NgModule({
    imports: [CommonModule],
    providers: [
        { provide: ABOUT_API_FACTORY_TOKEN, useClass: AboutApiLegacyFactory },
        { provide: ACTIONS_API_FACTORY_TOKEN, useClass: ActionsApiLegacyFactory },
        { provide: ACTIVITI_COMMENTS_API_FACTORY_TOKEN, useClass: ActivitiCommentsApiLegacyFactory },
        { provide: ACTIVITI_CONTENT_API_FACTORY_TOKEN, useClass: ActivitiContentApiLegacyFactory },
        { provide: ACTIVITI_GROUPS_API_FACTORY_TOKEN, useClass: ActivitiGroupsApiLegacyFactory },
        { provide: ASPECTS_API_FACTORY_TOKEN, useClass: AspectsApiLegacyFactory },
        { provide: AUDIT_API_FACTORY_TOKEN, useClass: AuditApiLegacyFactory },
        { provide: AUTHENTICATION_API_FACTORY_TOKEN, useClass: AuthenticationApiLegacyFactory },
        { provide: CHECKLISTS_API_FACTORY_TOKEN, useClass: ChecklistsApiLegacyFactory },
        { provide: CLASSES_API_FACTORY_TOKEN, useClass: ClassesApiLegacyFactory },
        { provide: COMMENTS_API_FACTORY_TOKEN, useClass: CommentsApiLegacyFactory },
        { provide: CONTENT_API_FACTORY_TOKEN, useClass: ContentApiLegacyFactory },
        { provide: CUSTOM_MODEL_API_FACTORY_TOKEN, useClass: CustomModelApiLegacyFactory },
        { provide: DISCOVERY_API_FACTORY_TOKEN, useClass: DiscoveryApiLegacyFactory },
        { provide: DOWNLOADS_API_FACTORY_TOKEN, useClass: DownloadsApiLegacyFactory },
        { provide: FAVORITES_API_FACTORY_TOKEN, useClass: FavoritesApiLegacyFactory },
        { provide: FILES_API_FACTORY_TOKEN, useClass: FilesApiLegacyFactory },
        { provide: FORM_MODELS_API_FACTORY_TOKEN, useClass: FormModelsApiLegacyFactory },
        { provide: GROUPS_API_FACTORY_TOKEN, useClass: GroupsApiLegacyFactory },
        { provide: INTEGRATION_ALFRESCO_ON_PREMISE_API_FACTORY_TOKEN, useClass: IntegrationAlfrescoOnPremiseApiLegacyFactory },
        { provide: MODELS_API_FACTORY_TOKEN, useClass: ModelsApiLegacyFactory },
        { provide: MODEL_JSON_BPMN_API_FACTORY_TOKEN, useClass: ModelJsonBpmnApiLegacyFactory },
        { provide: NODES_API_FACTORY_TOKEN, useClass: NodesApiLegacyFactory },
        { provide: PEOPLE_API_FACTORY_TOKEN, useClass: PeopleApiLegacyFactory },
        { provide: PROCESS_DEFINITIONS_API_FACTORY_TOKEN, useClass: ProcessDefinitionsApiLegacyFactory },
        { provide: PROCESS_INSTANCES_API_FACTORY_TOKEN, useClass: ProcessInstancesApiLegacyFactory },
        { provide: PROCESS_INSTANCE_VARIABLES_API_FACTORY_TOKEN, useClass: ProcessInstanceVariablesApiLegacyFactory },
        { provide: QUERIES_API_FACTORY_TOKEN, useClass: QueriesApiLegacyFactory },
        { provide: RATINGS_API_FACTORY_TOKEN, useClass: RatingsApiLegacyFactory },
        { provide: RECORDS_API_FACTORY_TOKEN, useClass: RecordsApiLegacyFactory },
        { provide: RENDITIONS_API_FACTORY_TOKEN, useClass: RenditionsApiLegacyFactory },
        { provide: REPORT_API_FACTORY_TOKEN, useClass: ReportApiLegacyFactory },
        { provide: RUNTIME_APP_DEFINITIONS_API_FACTORY_TOKEN, useClass: RuntimeAppDefinitionsApiLegacyFactory },
        { provide: SCRIPT_FILES_API_FACTORY_TOKEN, useClass: ScriptFilesApiLegacyFactory },
        { provide: SEARCH_API_FACTORY_TOKEN, useClass: SearchApiLegacyFactory },
        { provide: SECURITY_GROUPS_API_FACTORY_TOKEN, useClass: SecurityGroupsApiLegacyFactory },
        { provide: SECURITY_MARKS_API_FACTORY_TOKEN, useClass: SecurityMarksApiLegacyFactory },
        { provide: SHARED_LINKS_API_FACTORY_TOKEN, useClass: SharedLinksApiLegacyFactory },
        { provide: SITES_API_FACTORY_TOKEN, useClass: SitesApiLegacyFactory },
        { provide: SYSTEM_PROPERTIES_API_FACTORY_TOKEN, useClass: SystemPropertiesApiLegacyFactory },
        { provide: TAGS_API_FACTORY_TOKEN, useClass: TagsApiLegacyFactory },
        { provide: TASK_ACTIONS_API_FACTORY_TOKEN, useClass: TaskActionsApiLegacyFactory },
        { provide: TASK_FORMS_API_FACTORY_TOKEN, useClass: TaskFormsApiLegacyFactory },
        { provide: TASKS_API_FACTORY_TOKEN, useClass: TasksApiLegacyFactory },
        { provide: TRASHCAN_API_FACTORY_TOKEN, useClass: TrashcanApiLegacyFactory },
        { provide: TYPES_API_FACTORY_TOKEN, useClass: TypesApiLegacyFactory },
        { provide: UPLOAD_API_FACTORY_TOKEN, useClass: UploadApiLegacyFactory },
        { provide: USERS_API_FACTORY_TOKEN, useClass: UsersApiLegacyFactory },
        { provide: USER_FILTERS_API_FACTORY_TOKEN, useClass: UserFiltersApiLegacyFactory },
        { provide: USER_PROFILE_API_FACTORY_TOKEN, useClass: UserProfileApiLegacyFactory },
        { provide: VERSIONS_API_FACTORY_TOKEN, useClass: VersionsApiLegacyFactory },
        { provide: WEBSCRIPT_API_FACTORY_TOKEN, useClass: WebscriptApiLegacyFactory }
    ]
})
export class JsApiLegacyFactoriesModule {}
