name: "Upload build artifacts"
description: "Upload build artifacts"

runs:
  using: "composite"
  steps:
    - name: tar and upload artifacts
      shell: bash
      env:
        REMOTE_PATH: "alfresco-ng2-components/build-cache/${{ github.run_id }}"
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        packages=( dist nxcache node_modules )
        for i in "${packages[@]}"; do
          time tar czf $i.tar.gz $i
          du -h $i.tar.gz
          time aws s3 cp --no-progress $i.tar.gz "s3://${S3_BUILD_BUCKET_SHORT_NAME}/${REMOTE_PATH}/$i.tar.gz"
        done


