name: "Upload build artifacts"
description: "Upload build artifacts"

runs:
  using: "composite"
  steps:
    - name: Save dist to cache
      uses: actions/cache/save@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
      with:
        path: dist
        key: dist-${{ github.run_id }}-${{ github.run_attempt }}

    - name: Save nxcache to cache
      uses: actions/cache/save@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
      with:
        path: nxcache
        key: nxcache-${{ github.run_id }}-${{ github.run_attempt }}

    - name: Save node_modules to cache
      uses: actions/cache/save@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
      with:
        path: node_modules
        key: node-modules-${{ github.run_id }}-${{ github.run_attempt }}


