name: "before-install"
description: "run before install script"
runs:
  using: "composite"
  steps:
    - name: Before install
      run: |
        bash -xv ./scripts/ci/job_hooks/before_install.sh "/tmp/github_vars.env"
        while read ENVVAR; do
          echo "$ENVVAR" >> $GITHUB_ENV
        done < "/tmp/github_vars.env"
      shell: bash
