name: "set npm tag"
description: "se NPM tag"

inputs:
  branch_name:
    description: "override GITHUB_REF_NAME"
    required: false
    default: ${{ github.ref_name }}

outputs:
  npm-tag:
    description: "NPM tag"
    value: ${{ steps.set-npm-tag.outputs.npm-tag }}

runs:
  using: "composite"
  steps:

    - name: set TAG_NPM
      id: set-npm-tag
      shell: bash
      env:
        BRANCH_NAME: ${{ inputs.branch_name }}
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            TAG_NPM="branch"
        else
          TAG_NPM="alpha"
          VERSION_IN_PACKAGE_JSON=$(node -p "require('./package.json')".version)
          echo "version in package.json=${VERSION_IN_PACKAGE_JSON}"
          if [[ $BRANCH_NAME =~ ^master(-patch.*)?$ ]]; then
              # Pre-release versions
              if [[ $VERSION_IN_PACKAGE_JSON =~ ^[0-9]*\.[0-9]*\.[0-9]*-A\.[0-9]*$ ]];
              then
                  TAG_NPM=next
              # Stable major versions
              else
                  TAG_NPM=latest
              fi
          fi
          if [[ $BRANCH_NAME =~ ^develop(-patch.*)?$ ]]; then
              TAG_NPM=alpha
          fi
        fi
        echo "npm-tag=$TAG_NPM" >> $GITHUB_OUTPUT
        echo $TAG_NPM
