name: "set npm tag"
description: "se NPM tag"

inputs:
  event_name:
    description: "override github.event_name"
    required: false
    default: ${{ github.event_name }}
  branch_name:
    description: "override GITHUB_REF_NAME"
    required: false
    default: $GITHUB_REF_NAME

runs:
  using: "composite"
  steps:

    - name: set TAG_NPM
      shell: bash
      run: |
        TAG_NPM="alpha"
        VERSION_IN_PACKAGE_JSON=$(node -p "require('./package.json')".version)
        echo "version in package.json=${VERSION_IN_PACKAGE_JSON}"
        if [[ ${{ inputs.branch_name }} =~ ^master(-patch.*)?$ ]]; then
            # Pre-release versions
            if [[ $VERSION_IN_PACKAGE_JSON =~ ^[0-9]*\.[0-9]*\.[0-9]*-A\.[0-9]*$ ]];
            then
                TAG_NPM=next
            # Stable major versions
            else
                TAG_NPM=latest
            fi
        fi
        if [[ ${{ inputs.branch_name }} =~ ^develop(-patch.*)?$ ]]; then
            TAG_NPM=alpha
        fi
        echo "TAG_NPM=${TAG_NPM}" >> $GITHUB_ENV
