name: 'Check NPM bundle'
description: 'check npm bundle'

outputs:
  tag_sha:
    description: "long sha of the tag"
    value: ${{ steps.sha_out.outputs.tag_sha }}

runs:
  using: "composite"

  steps:
    - name: load "TRAVIS_EVENT_TYPE"
      uses: ./.github/actions/travis-env-var-facade  
    - name: check npm bundle
      shell: bash
      id: sha_out
      run: |
          ADF_VERSION=$(npm view @alfresco/adf-core@${TAG_NPM} version)
          echo "check bundle on TAG_NPM='${TAG_NPM}' and ADF_VERSION='${ADF_VERSION}'"
          ./scripts/travis/build/npm-check-bundles.sh -v ${ADF_VERSION}