name: 'Npm check bundle'

outputs:
  tag_sha:
    description: "long sha of the tag"
    value: ${{ steps.sha_out.outputs.tag_sha }}

runs:
  using: "composite"
  steps:
    - name: npm check bundle
      env: 
        TAG_NPM: alpha
      shell: bash
      id: sha_out
      run: |
        set -u;
        export ADF_VERSION=$(npm view @alfresco/adf-core@${TAG_NPM} version)
        echo "ADF_VERSION='${ADF_VERSION}'"
        ./scripts/travis/build/npm-check-bundles.sh -v ${ADF_VERSION}
