name: Identify the slack group
description: 'Identify the slack group area based on the affected'

inputs:
  affected:
    description: 'The name of the affected lib'
    required: true
    type: string

outputs:
  groups:
    description: "the slack groups"
    value: ${{ steps.group.outputs.result }}

runs:
  using: "composite"

  steps:
    - name: Append group
      id: group
      uses: actions/github-script@v6
      env:
        affectedLib: ${{ inputs.affected }}
      with:
        script: |
          const affectedLib = process.env.affectedLib;
          core.info(`Input ${affectedLib}`);

          const slackGroups = new Set();
          const AlfrescoQAGroup = '@alfresco-testing-qa';
          const HxpQAGroup = '@hxp-studio-qa-group';

          const libs = affectedLib.split(' ')

          if (libs.includes('content-services') || libs.includes('process-services')) {
            slackGroups.add(AlfrescoQAGroup);
          } 
          if (libs.includes('process-services-cloud')) {
            slackGroups.add(HxpQAGroup);
          } 
          if (libs.includes('core')) {
            slackGroups.add(AlfrescoQAGroup);
            slackGroups.add(HxpQAGroup);
          }

          const result = Array.from(slackGroups.values()).join(' ');
          core.info(`Result ${result}`);
          return result;

