name: "Download build artifacts"
description: "Download build artifacts"
runs:
  using: "composite"
  steps:
    - name: Restore dist from cache
      uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: dist
        key: dist-${{ github.run_id }}-${{ github.run_attempt }}
        fail-on-cache-miss: true

    - name: Restore nxcache from cache
      uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: nxcache
        key: nxcache-${{ github.run_id }}-${{ github.run_attempt }}
        fail-on-cache-miss: true

    - name: Restore node_modules from cache
      uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: node_modules
        key: node-modules-${{ github.run_id }}-${{ github.run_attempt }}
        fail-on-cache-miss: true

    - name: show files
      shell: bash
      run: |
        pwd
        ls -lha
        echo "====DIST===="
        find dist -maxdepth 1 -type d
        echo "====NXCACHE===="
        find nxcache -maxdepth 1 -type d
        echo "====ADF===="
        find node_modules/@alfresco/ -maxdepth 1 -type d
