name: 'Install Google Chrome'
description: 'Install Google Chrome'

runs:
  using: "composite"
  steps:
      - name: Install google chrome
        shell: bash
        run: |
          wget -q https://mirror.cs.uchicago.edu/google-chrome/pool/main/g/google-chrome-stable/google-chrome-stable_114.0.5735.106-1_amd64.deb
          sudo apt install -y --allow-downgrades ./google-chrome-stable_114.0.5735.106-1_amd64.deb
            sudo ln -s /usr/bin/google-chrome /usr/bin/chrome
            chrome --version
