name: Initialize Artifact
description: 'Allow the user to initialize an empty artifact used globally'

inputs:
  artifact-name:
    description: 'The name of the artifact'
    required: true
    type: string
  file-name:
    description: 'The name of the file with extension created in the artifact'
    required: true
    type: string
  content:
    description: 'The init content the file should have'
    type: string
    default: ""

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Create empty artifact
      shell: bash
      run:
        echo "${{inputs.content}}" > ${{ inputs.file-name }}

    - name: Upload artifact
      uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.file-name }}
