name: Initialize Artifact
description: 'Allow the user to initialize an empty artifact used globally'

inputs:
  artifact-name:
    description: 'The name of the artifact'
    required: true
    type: string
  file-name:
    description: 'The name of the file with extension created in the artifact'
    required: true
    type: string
  content:
    description: 'The init content the file should have'
    type: string
    default: ""

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - name: Create empty artifact
      shell: bash
      run:
        echo "${{inputs.content}}" > ${{ inputs.file-name }}

    - name: Upload artifact
      uses: actions/upload-artifact@1eb3cb2b3e0f29609092a73eb033bb759a334595 # v4.1.0
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.file-name }}
