name: "print affected libs"
description: "Retrive the affected libs based on the based and head input"
inputs:
  base:
    description: 'the base sha'
    required: true
    type: string
    default: main
  head:
    description: 'the head sha'
    required: true
    type: string
    default: HEAD
output:
  affected:
    description: 'the affected libs of the repo'
  affected_is_empty:
   description: 'true or false accondingly'
runs:
  using: "node16"
  main: 'dist/index.js'