name: "Setup"
description: "Build setup"
inputs:
  who-to-greet: # id of input
    description: "Who to greet"
    required: false
    default: "World"
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    ## NXCACHE
    - name: update NX cache folder
      uses: actions/download-artifact@v3
      continue-on-error: true
      with:
        path: nxcache.tar.gz
        name: nxcache-${{ github.ref_name }}
    ## DIST
    - name: update Dist folder
      uses: actions/download-artifact@v3
      continue-on-error: true
      with:
        path: dist.tar.gz
        name: dist-${{ github.ref_name }}
    - name: extract cache
      run: |
        tar xzf nxcache.tar.gz -C ${{ github.workspace }}
        tar xzf dist.tar.gz -C ${{ github.workspace }}
      shell: bash