name: "Setup"
description: "Build setup"
inputs:
  who-to-greet: # id of input
    description: "Who to greet"
    required: false
    default: "World"
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    ## NXCACHE
    - name: tar artifacts
      run: |
        time tar czf dist.tar.gz ${{ github.workspace }}/dist
        time tar czf nxcache.tar.gz ${{ github.workspace }}/nxcache
      shell: bash
    - name: update NX cache folder
      uses: actions/upload-artifact@v3
      continue-on-error: true
      with:
        path: nxcache.tar.gz
        name: nxcache-${{ github.ref_name }}
    ## DIST
    - name: update Dist folder
      uses: actions/upload-artifact@v3
      continue-on-error: true
      with:
        path: dist.tar.gz
        name: dist-${{ github.ref_name }}
