name: "clean test env"
description: "clean test env"
runs:
  using: "composite"
  steps:
    - name: cleanup test env
      shell: bash
      run: |
        xvfb_pid=$(ps x | grep -v grep | grep xvfb-run | awk '{print $1}')
        if [ "$xvfb_pid" != "" ]; then
            echo "Killing the following xvfb process: $xvfb_pid"
            sudo kill $xvfb_pid || true
        else
            echo "Nothing to kill"
        fi