name: Extract Artifact
description: 'Allow the user to extract content from an artifact'

inputs:
  artifact-name:
    description: 'The name of the artifact'
    required: true
    type: string
  file-name:
    description: 'The name of the file with extension created in the artifact'
    required: true
    type: string
  content:
    description: 'The init content the file should have'
    type: string
    default: ""

outputs:
  result:
    description: "the value extrated from the file inside the artifact"
    value: ${{ steps.extract.outputs.result }}

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - run: echo "Artifact Extract"
      shell: bash
    - name: Download artifact
      uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4.3.6
      with:
        name: ${{ inputs.artifact-name }}
        pattern: ${{ inputs.artifact-name }}-*
        merge-multiple: true
    - id: extract
      shell: bash
      run: |
        value=`cat ${{ inputs.file-name }}`
        echo "print $value"
        echo "result=$value" >> $GITHUB_OUTPUT

