name: Extract Artifact
description: 'Allow the user to extract content from an artifact'

inputs:
  artifact-name:
    description: 'The name of the artifact'
    required: true
    type: string
  file-name:
    description: 'The name of the file with extension created in the artifact'
    required: true
    type: string
  content:
    description: 'The init content the file should have'
    type: string
    default: ""

outputs:
  result:
    description: "the value extrated from the file inside the artifact"
    value: ${{ steps.extract.outputs.result }}

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
    - run: echo "Artifact Extract"
      shell: bash
    - name: Download artifact
      uses: actions/upload-artifact@1746f4ab65b179e0ea60a494b83293b640dd5bba # v4.3.2
      with:
        name: ${{ inputs.artifact-name }}
        pattern: ${{ inputs.artifact-name }}-*
        merge-multiple: true
    - id: extract
      shell: bash
      run: |
        value=`cat ${{ inputs.file-name }}`
        echo "print $value"
        echo "result=$value" >> $GITHUB_OUTPUT

