name: Extract Artifact
description: 'Allow the user to extract content from an artifact'

inputs:
  artifact-name:
    description: 'The name of the artifact'
    required: true
    type: string
  file-name:
    description: 'The name of the file with extension created in the artifact'
    required: true
    type: string
  content:
    description: 'The init content the file should have'
    type: string
    default: ""

outputs:
  result:
    description: "the value extrated from the file inside the artifact"
    value: ${{ steps.extract.outputs.result }}

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - run: echo "Artifact Extract"
      shell: bash
    - name: Download artifact
      uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935 # v4.1.1
      with:
        name: ${{ inputs.artifact-name }}
    - id: extract
      shell: bash
      run: |
        value=`cat ${{ inputs.file-name }}`
        echo "print $value"
        echo "result=$value" >> $GITHUB_OUTPUT

