name: "alpha-adf"

on:  
  workflow_call:  
  workflow_dispatch:
    inputs:
      cluster_operation:
        description: trigger adf test
        type: choice
        required: true
        options:
          - TRIGGER_ALPHA_ADF          
        default: TRIGGER_ALPHA_ADF

jobs:
  trigger_adf:
    name: trigger adf test
    runs-on: ubuntu-latest  
    steps:     
        - name: Checkout repository
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Trigger Alpha ADF child build
          shell: bash
          if: ${{ contains(github.event.head_commit.message, '[trigger adf]') || inputs.cluster_operation == 'TRIGGER_ALPHA_ADF' || github.event.schedule == '0 14 * * *' }}
          run: ./scripts/travis/update/update-project.sh -p $TRAVIS_BUILD_NUMBER -t $GITHUB_TOKEN -v alpha -c $TRAVIS_COMMIT
          