on:
  pull_request:
    types:
      - closed

env:
  TRAVIS_BRANCH: ${{ github.ref_name }}
  GITHUB_BRANCH: ${{ github.ref_name }}
  TRAVIS_BUILD_DIR: ${{ github.workspace }}
  TRAVIS_COMMIT: ${{ github.sha }}
  TRAVIS_BUILD_ID: ${{ github.run_id }}
  TRAVIS_RUN_NUMBER: ${{ github.run_attempt }}
  E2E_HOST_APA: ${{ secrets.E2E_HOST_APA }}
  E2E_HOST: ${{ secrets.E2E_HOST }}
  E2E_USERNAME: ${{ secrets.E2E_ADMIN_EMAIL_IDENTITY }}
  E2E_PASSWORD: ${{ secrets.E2E_PASSWORD }}
  E2E_ADMIN_EMAIL_IDENTITY: ${{ secrets.E2E_ADMIN_EMAIL_IDENTITY }}
  E2E_ADMIN_PASSWORD_IDENTITY: ${{ secrets.E2E_ADMIN_PASSWORD_IDENTITY }}
  USERNAME_ADF: ${{ secrets.E2E_USERNAME }}
  PASSWORD_ADF: ${{ secrets.E2E_PASSWORD }}
  URL_HOST_ADF: ${{ secrets.URL_HOST_ADF }}  
  IDENTITY_ADMIN_EMAIL: ${{ secrets.E2E_ADMIN_EMAIL_IDENTITY }}
  IDENTITY_ADMIN_PASSWORD: ${{ secrets.E2E_ADMIN_PASSWORD_IDENTITY }}
  AWS_S3_BUCKET_ACTIVITI_LICENSE: ${{ secrets.AWS_S3_BUCKET_ACTIVITI_LICENSE }}
  HOST_SSO: ${{ secrets.HOST_SSO }}
  LOG_LEVEL: "ERROR"
  E2E_LOG_LEVEL: "ERROR"
  PROXY_HOST_BPM: ${{ secrets.E2E_HOST }}
  E2E_MODELER_USERNAME: ${{ secrets.E2E_MODELER_USERNAME }}
  E2E_MODELER_PASSWORD: ${{ secrets.E2E_MODELER_PASSWORD }}
  EXTERNAL_ACS_HOST: ${{ secrets.EXTERNAL_ACS_HOST }}
  E2E_DEVOPS_USERNAME: ${{ secrets.E2E_DEVOPS_USERNAME }}
  E2E_DEVOPS_PASSWORD: ${{ secrets.E2E_DEVOPS_PASSWORD }}




jobs:
  main:
    timeout-minutes: 20
    if: github.event.pull_request.merged == true
    name: "Build Components"
    runs-on: ubuntu-22.04
    env:
      TRAVIS_BRANCH: develop
      # TRAVIS_EVENT_TYPE: push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches
      - uses: ./.github/actions/setup
      - name: debug nx-set-sha
        run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"
      - run: echo $TRAVIS_EVENT_TYPE
      - run: echo $S3_NODE_MODULES_CACHE_ID
      - run: echo $HEAD_COMMIT_HASH
      - run: echo $NX_CALCULATION_FLAGS
      - run: npm ci
      - run: npx nx affected $NX_CALCULATION_FLAGS --target=lint --parallel=3
      - run: nx affected:build $NX_CALCULATION_FLAGS --prod --exclude="demoshell"
      - run: nx $NX_CALCULATION_FLAGS build demoshell --configuration production
      - run: nx build demoshell --configuration production
      - uses: ./.github/actions/upload-artifacts

      - name: Release
        run: |
          set -u;
          ./scripts/travis/build/bumpversion.sh
          time $(npm bin)/nx affected:build $NX_CALCULATION_FLAGS --prod --exclude="demoshell" # TODO ??
          time $(npm bin)/nx affected $NX_CALCULATION_FLAGS --target=pretheme
          ./scripts/travis/release/release-npm.sh


      - name: push Demoshell docker image
        run: |
          set -u;        
          $(npm bin)/nx build demoshell --configuration production
          . ./scripts/travis/release/docker-tag.sh
          ./scripts/travis/release/release-demoshell-docker.sh

      - run: nx run stories:build-storybook --configuration ci

      - name: push Storybook docker image
        run: |
          set -u;        
          $(npm bin)/nx run stories:build-storybook --configuration ci
          . ./scripts/travis/release/docker-tag.sh
          ./scripts/travis/release/release-storybook-docker.sh 


      - name: Check npm bundle
        run: |
          ADF_VERSION=$(npm view @alfresco/adf-core@${TAG_NPM} version)
          ./scripts/travis/build/npm-check-bundles.sh -v ${ADF_VERSION}
