name: "cron e2e daily"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1-5' #At 12:00 on every day-of-week from Monday through Friday.

env:
  BASE_REF: ${{ github.base_ref }}
  HEAD_REF: ${{ github.head_ref }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  GITHUB_BRANCH: ${{ github.ref_name }}
  GH_BUILD_DIR: ${{ github.workspace }}
  GH_COMMIT: ${{ github.sha }}
  BUILD_ID: ${{ github.run_id }}
  GH_RUN_NUMBER: ${{ github.run_attempt }}
  GH_BUILD_NUMBER: ${{ github.run_id }}
  JOB_ID: ${{ github.run_id }}
  PROXY_HOST_BPM: ${{ secrets.E2E_HOST }}
  E2E_HOST_APA: ${{ secrets.E2E_HOST_APA }}
  E2E_IDENTITY_HOST_APA: ${{ secrets.E2E_IDENTITY_HOST_APA }}
  E2E_HOST: ${{ secrets.E2E_HOST }}
  E2E_USERNAME: ${{ secrets.E2E_ADMIN_EMAIL_IDENTITY }}
  E2E_PASSWORD: ${{ secrets.E2E_PASSWORD }}
  E2E_ADMIN_EMAIL_IDENTITY: ${{ secrets.E2E_ADMIN_EMAIL_IDENTITY }}
  E2E_ADMIN_PASSWORD_IDENTITY: ${{ secrets.E2E_ADMIN_PASSWORD_IDENTITY }}
  USERNAME_ADF: ${{ secrets.E2E_ADMIN_EMAIL_IDENTITY }}
  PASSWORD_ADF: ${{ secrets.E2E_PASSWORD }}
  URL_HOST_ADF: "http://localhost:4200"
  IDENTITY_ADMIN_EMAIL: ${{ secrets.E2E_ADMIN_EMAIL_IDENTITY }}
  IDENTITY_ADMIN_PASSWORD: ${{ secrets.E2E_ADMIN_PASSWORD_IDENTITY }}
  AWS_S3_BUCKET_ACTIVITI_LICENSE: ${{ secrets.AWS_S3_BUCKET_ACTIVITI_LICENSE }}
  HOST_SSO: ${{ secrets.HOST_SSO }}
  LOG_LEVEL: "ERROR"
  E2E_LOG_LEVEL: "ERROR"
  E2E_MODELER_USERNAME: ${{ secrets.E2E_MODELER_USERNAME }}
  E2E_MODELER_PASSWORD: ${{ secrets.E2E_MODELER_PASSWORD }}
  EXTERNAL_ACS_HOST: ${{ secrets.EXTERNAL_ACS_HOST }}
  E2E_DEVOPS_USERNAME: ${{ secrets.E2E_DEVOPS_USERNAME }}
  E2E_DEVOPS_PASSWORD: ${{ secrets.E2E_DEVOPS_PASSWORD }}
  USERNAME_SUPER_ADMIN_ADF: ${{ secrets.USERNAME_SUPER_ADMIN_ADF }}
  PASSWORD_SUPER_ADMIN_ADF: ${{ secrets.PASSWORD_SUPER_ADMIN_ADF }}
  HR_USER: ${{ secrets.HR_USER }}
  HR_USER_PASSWORD: ${{ secrets.HR_USER_PASSWORD }}
  SMART_RUNNER_PATH: ".protractor-smartrunner"
  S3_DBP_PATH:  ${{ secrets.S3_DBP_PATH }}
  S3_BUILD_BUCKET_SHORT_NAME: ${{ secrets.S3_BUILD_BUCKET_SHORT_NAME }}
  NODE_OPTIONS: "--max-old-space-size=5120"
  DOCKER_REPOSITORY_DOMAIN: ${{ secrets.DOCKER_REPOSITORY_DOMAIN }}
  DOCKER_REPOSITORY_USER: ${{ secrets.DOCKER_REPOSITORY_USER }}
  DOCKER_REPOSITORY_PASSWORD: ${{ secrets.DOCKER_REPOSITORY_PASSWORD }}
  DOCKER_REPOSITORY_STORYBOOK: "${{ secrets.DOCKER_REPOSITORY_DOMAIN }}/alfresco/storybook"
  DOCKER_REPOSITORY: "${{ secrets.DOCKER_REPOSITORY_DOMAIN }}/alfresco/demo-shell"
  REPO_OWNER: "Alfresco"
  REPO_NAME: "alfresco-ng2-components"
  DEMO_SHELL_DIR: "./dist/demo-shell"
  STORYBOOK_DIR: "./dist/storybook/stories"
  BUILT_LIBS_DIR: "./dist/libs"
  NODE_MODULES_DIR: "./node_modules"
  SMART_RUNNER_DIRECTORY: ".protractor-smartrunner"
  SAVE_SCREENSHOT: true
  REDIRECT_URI: /
  BROWSER_RUN: false
  MAXINSTANCES: 2
  PLAYWRIGHT_WORKERS: 2
  PLAYWRIGHT_STORYBOOK_E2E_HOST: http://localhost
  PLAYWRIGHT_STORYBOOK_E2E_PORT: 4400
  PROXY_HOST_ECM: ${{ secrets.E2E_HOST }}

jobs:
  test-redeploy:
    runs-on: ubuntu-latest
    name: Test redeploy
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          repository: Alfresco/hxp-frontend-apps
          ref: develop
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
      - name: Redeploy default apps
        uses: ./.github/actions/redeploy-app
        with:
          gh-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          gh-packages-read-only-token: ${{ secrets.HYLAND_GH_PACKAGES_READ_ONLY_TOKEN }}
          secretsMasterPassword: ${{ secrets.CI_MASTER_PASSWORD }}
          environment: hxpsRc
          system: hxp
  init-artifact:
    if: false
    runs-on: ubuntu-latest
    name: Initialize artifacts
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - uses: ./.github/actions/artifact-initialize
        with:
          artifact-name: global-e2e-result
          file-name: e2e-failures.txt

  run-e2e:
    if: false
    name: run e2e
    uses: ./.github/workflows/pull-request.yml
    with:
      cron-run: true
    secrets: inherit
