name: "dev-build"

on:
  push:
    branches:
      - AAE-7986-dev-act
      #
      #   - /^master(-patch.*)?$/
      #   - /^develop(-patch.*)?$/
      #   - master
      #   - develop
      # #remove after upgrade
      #   - angular-14-rebase
      #   - /.*old-env.*/
      #   - /.*next-release.*/
      #   - /.*beta.*/


# on:
#   pull_request:
#     types: [opened, reopened]
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
env:
  TRAVIS_BRANCH: ${{ github.ref_name }}
  GITHUB_BRANCH: ${{ github.ref_name }}
  TRAVIS_BUILD_DIR: ${{ github.workspace }}
  TRAVIS_COMMIT: ${{ github.sha }}
  TRAVIS_BUILD_ID: ${{ github.run_id }}

jobs:
  prerequisite:
    name: "Before anything unnece$$ary happens..."
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches
## PIP CACHE
      - name: pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-
          restore-keys: |
            ${{ runner.os }}           
      - name: load "TRAVIS_EVENT_TYPE"
        uses: ./.github/actions/travis-event-type-load    
      - name: before install
        uses: ./.github/actions/before-install
      - run: echo $S3_NODE_MODULES_CACHE_ID
      - run: echo $HEAD_COMMIT_HASH
      - run: echo $NX_CALCULATION_FLAGS    
      - name: build guard check
        if: ${{ github.event_name == 'pull_request' }}
        run: ./scripts/ci/jobs/dbpci-build-guard-check $TRAVIS_PULL_REQUEST || exit 1

  build-lib:
    name: "Build Lib"
    needs: prerequisite
    runs-on: ubuntu-22.04
    env:
      TRAVIS_BRANCH: develop
      # TRAVIS_EVENT_TYPE: push
    steps:
# PREPARATION
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches
      - name: install NPM
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache-dependency-path: package-lock.json
# CACHE
## MODULES
      - name: Node modules cache
        id: cache-node-modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-modules-${{ runner.os }}-build-${{ env.cache-name }}-
            node-modules-${{ runner.os }}-build-
            node-modules-${{ runner.os }}-
## .NPM
      - name: Node cache
        id: cache-npm 
        uses: actions/cache@v3
        env:
          cache-name: npm-node-modules
        with: 
          path: ~/.npm
          # TODO find a more suitable key
          key: .npm-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            .npm-${{ runner.os }}-build-${{ env.cache-name }}-
            .npm-${{ runner.os }}-build-
            .npm-${{ runner.os }}-
## PIP
      - name: pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-
          restore-keys: |
            ${{ runner.os }}   
## NXCACHE
      - name: get NX cache folder
        uses: actions/download-artifact@v3
        continue-on-error: true
        with:
          path: nxcache/
          name: nxcache-${{ github.ref_name }}
## DIST
      - name: get Dist folder
        uses: actions/download-artifact@v3
        continue-on-error: true
        with:
          path: dist/
          name: dist-${{ github.ref_name }}
## SMARTRUNNER
      - name: Get Smartrunner folder
        uses: actions/download-artifact@v3
        continue-on-error: true
        with:
          path: .protractor-smartrunner/
          name: smartrunner-${{ github.ref_name }}

# PREREQUISITES
      # - name: install Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.9'
      #     cache: 'pip'
# ENV LOAD
      - uses: Alfresco/alfresco-build-tools/.github/actions/travis-env-load@v1.17.0
        with:
          yml_path: .travis.yml
      - name: load "TRAVIS_EVENT_TYPE"
        uses: ./.github/actions/travis-event-type-load
      - name: before install
        uses: ./.github/actions/before-install          
      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'develop'
      - name: debug nx-set-sha
        run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"
# BUILD

      # - if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }} || ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
      - run: echo $TRAVIS_EVENT_TYPE
      - run: echo $S3_NODE_MODULES_CACHE_ID
      - run: echo $HEAD_COMMIT_HASH
      - run: echo $NX_CALCULATION_FLAGS
      - run: npm ci
      - run: npx nx affected --target=lint --parallel=3
      # - name: Update NX settings to use DEV branch
      #   uses: mikefarah/yq@v4.28.1
      #   with:
      #     cmd: yq -i '.affected.defaultBase = env(GITHUB_BRANCH)' nx.json
      # - name: Lib::Build
      #   run: |
      #     sudo ln -s $(npm bin)/nx /usr/bin/nx
      #     bash -xeo pipefail ./scripts/travis/build/build-libs.sh
        # bump
        # bash ./scripts/travis/release/release-npm.sh # launch npm-publish
      # ./scripts/travis/release/release-npm.sh || exit 1
      # - name: Cache node modules
      #   uses: actions/cache@v3
      #   with:
      #     path: $NODE_MODULES_DIR
      #     key: v1-npm-deps-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: v1-npm-deps-


# UPDATE BUILD CACHE
## NXCACHE
      - name: get NX cache folder
        uses: actions/upload-artifact@v3
        with:
          path: nxcache/
          name: nxcache-${{ github.ref_name }}
# ## DIST
#       - name: get Dist folder
#         uses: actions/upload-artifact@v3
#         with:
#           path: dist/
#           name: dist-${{ github.ref_name }}
# ## SMARTRUNNER
#       - name: Get Smartrunner folder
#         uses: actions/upload-artifact@v3
#         with:
#           path: .protractor-smartrunner/
#           name: smartrunner-${{ github.ref_name }}

