name: "dev-build"

on:
  push:
    branches:
      - AAE-7986-dev-act
      #
      #   - /^master(-patch.*)?$/
      #   - /^develop(-patch.*)?$/
      #   - master
      #   - develop
      # #remove after upgrade
      #   - angular-14-rebase
      #   - /.*old-env.*/
      #   - /.*next-release.*/
      #   - /.*beta.*/

# on:
#   pull_request:
#     types:
#       - closed

# jobs:
#   if_merged:
#     if: github.event.pull_request.merged == true
#     runs-on: ubuntu-latest
#     steps:
#     - run: |
#         echo The PR was merged

# on:
#   pull_request:
#     types: [opened, reopened]
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
env:
  TRAVIS_BRANCH: ${{ github.ref_name }}
  GITHUB_BRANCH: ${{ github.ref_name }}
  TRAVIS_BUILD_DIR: ${{ github.workspace }}
  TRAVIS_COMMIT: ${{ github.sha }}
  TRAVIS_BUILD_ID: ${{ github.run_id }}

jobs:
  main:
    name: "Build Lib"
    runs-on: ubuntu-22.04
    # TODO : pull request not merged
    # if: github.event.pull_request.merged == true
    env:
      TRAVIS_BRANCH: develop
      # TRAVIS_EVENT_TYPE: push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches
      - name: install NPM
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache-dependency-path: package-lock.json
      - name: Node cache
        id: node-cache
        uses: actions/cache@v3
        env:
          cache-name: node-cache
        with:
          path: |
            node_modules
            ~/.npm
          key: .npm-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-${{ runner.os }}-build-${{ env.cache-name }}-
            node-${{ runner.os }}-build-
            node-${{ runner.os }}-
      - name: pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-
          restore-keys: |
            ${{ runner.os }}   

# ENV LOAD
      - uses: Alfresco/alfresco-build-tools/.github/actions/travis-env-load@v1.17.0
        with:
          yml_path: .travis.yml
      - name: load "TRAVIS_EVENT_TYPE"
        uses: ./.github/actions/travis-event-type-load
      - name: before install
        uses: ./.github/actions/before-install
      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'develop'
      - name: debug nx-set-sha
        run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"
# BUILD

      # - if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }} || ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
      - name: override NX_CALCULATION_FLAGS
        run: echo 'NX_CALCULATION_FLAGS=--base=origin/develop --head=HEAD' >> $GITHUB_ENV
      - run: echo $TRAVIS_EVENT_TYPE
      - run: echo $S3_NODE_MODULES_CACHE_ID
      - run: echo $HEAD_COMMIT_HASH
      - run: echo $NX_CALCULATION_FLAGS
      - run: npm ci
      - run: npx nx affected $NX_CALCULATION_FLAGS --target=lint --parallel=3
      - name: install chrome      
        uses: browser-actions/setup-chrome@latest
      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npx nx affected:test $NX_CALCULATION_FLAGS --exclude="insights,core,extensions,process-services,process-services-cloud" }}
      - run: nx affected:build $NX_CALCULATION_FLAGS --prod --exclude="demoshell"
      - run: nx $NX_CALCULATION_FLAGS build demoshell --configuration production 
      - run: nx run stories:build-storybook --configuration ci
