name: "dev-build"

on:
  push:
    branches: 
      - AAE-7986-dev-act
      #
      #   - /^master(-patch.*)?$/
      #   - /^develop(-patch.*)?$/
      #   - master
      #   - develop
      # #remove after upgrade
      #   - angular-14-rebase
      #   - /.*old-env.*/
      #   - /.*next-release.*/
      #   - /.*beta.*/

env:
  NODE_MODULES_DIR: "./node_modules"
  TRAVIS_BRANCH: ${{ github.ref_name }}
  TRAVIS_BUILD_DIR: ${{ github.workspace }}
  TRAVIS_COMMIT: ${{ github.sha }}

jobs:
  prerequisite:
    name: "Before anything unnece$$ary happens..."
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: build guard check
        if: ${{ github.event_name == 'pull_request' }}
        run: ./scripts/ci/jobs/dbpci-build-guard-check $TRAVIS_PULL_REQUEST || exit 1

  build-lib:
    name: "Lib::Build"
    needs: prerequisite
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: install NPM
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Build::lib
        run: | 
          echo $GITHUB_WORKSPACE
          echo $PWD
          echo $TRAVIS_BRANCH
          echo $TRAVIS_BUILD_DIR
          echo $TRAVIS_COMMIT
          ./scripts/travis/build/build-libs.sh || exit 1
      # ./scripts/travis/release/release-npm.sh || exit 1
      # - name: Cache node modules
      #   uses: actions/cache@v3
      #   with:
      #     path: $NODE_MODULES_DIR
      #     key: v1-npm-deps-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: v1-npm-deps-
