name: "dev-build"

on:
  push:
    branches:
      - AAE-7986-dev-act
      #
      #   - /^master(-patch.*)?$/
      #   - /^develop(-patch.*)?$/
      #   - master
      #   - develop
      # #remove after upgrade
      #   - angular-14-rebase
      #   - /.*old-env.*/
      #   - /.*next-release.*/
      #   - /.*beta.*/

env:
  TRAVIS_BRANCH: ${{ github.ref_name }}
  GITHUB_BRANCH: ${{ github.ref_name }}
  TRAVIS_BUILD_DIR: ${{ github.workspace }}
  TRAVIS_COMMIT: ${{ github.sha }}
  TRAVIS_BUILD_ID: ${{ github.run_id }}

jobs:
  prerequisite:
    name: "Before anything unnece$$ary happens..."
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: build guard check
        if: ${{ github.event_name == 'pull_request' }}
        run: ./scripts/ci/jobs/dbpci-build-guard-check $TRAVIS_PULL_REQUEST || exit 1

  build-lib:
    name: "Build Lib"
    needs: prerequisite
    runs-on: ubuntu-18.04
    env:
      TRAVIS_BRANCH: develop
      TRAVIS_EVENT_TYPE: push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: install NPM
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: debug nx
        run: | 
          npm bin
      - name: install Python
        uses: actions/setup-python@v4
        with:
          python-version: '2.7'
      - uses: Alfresco/alfresco-build-tools/.github/actions/travis-env-load@v1.17.0
        with:
          yml_path: .travis.yml
      - name: before install
        run: bash -u ./scripts/ci/job_hooks/before_install.sh
      - name: install
        run: bash -u ./scripts/ci/job_hooks/install.sh
      - name: Update NX settings to use DEV branch
        uses: mikefarah/yq@v4.28.1
        with:
          cmd: yq -i '.affected.defaultBase = env(GITHUB_BRANCH)' nx.json
      - name: Lib::Build
        run: |
          sudo ln -s $(npm bin)/nx /usr/bin/nx
          bash -u ./scripts/travis/build/build-libs.sh
        # bash ./scripts/travis/release/release-npm.sh # launch npm-publish
      # ./scripts/travis/release/release-npm.sh || exit 1
      # - name: Cache node modules
      #   uses: actions/cache@v3
      #   with:
      #     path: $NODE_MODULES_DIR
      #     key: v1-npm-deps-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: v1-npm-deps-
