name: "dev-build"

on:
  push:
    branches:
      - AAE-7986-dev-act
      #
      #   - /^master(-patch.*)?$/
      #   - /^develop(-patch.*)?$/
      #   - master
      #   - develop
      # #remove after upgrade
      #   - angular-14-rebase
      #   - /.*old-env.*/
      #   - /.*next-release.*/
      #   - /.*beta.*/

env:
  NODE_MODULES_DIR: "./node_modules"
  TRAVIS_BRANCH: ${{ github.ref_name }}
  TRAVIS_BUILD_DIR: ${{ github.workspace }}
  TRAVIS_COMMIT: ${{ github.sha }}

jobs:
  prerequisite:
    name: "Before anything unnece$$ary happens..."
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: build guard check
        if: ${{ github.event_name == 'pull_request' }}
        run: ./scripts/ci/jobs/dbpci-build-guard-check $TRAVIS_PULL_REQUEST || exit 1

  build-lib:
    name: "Build Lib"
    needs: prerequisite
    runs-on: ubuntu-18.04
    env:
      TRAVIS_BRANCH: develop
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: install NPM
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: install nx
        run: npm i -g nx
      - name: install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: Alfresco/alfresco-build-tools/.github/actions/travis-env-load@v1.17.0
        with:
          yml_path: .travis.yml
      - name: before install
        run: bash ./scripts/ci/job_hooks/before_install.sh
      - name: install
        run: bash ./scripts/ci/job_hooks/install.sh
      - name: Lib::Build
        run: bash ./scripts/travis/build/build-libs.sh
      # ./scripts/travis/release/release-npm.sh || exit 1
      # - name: Cache node modules
      #   uses: actions/cache@v3
      #   with:
      #     path: $NODE_MODULES_DIR
      #     key: v1-npm-deps-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: v1-npm-deps-
