name: "dev-build"

on:
  push:
    branches:
      - AAE-7986-dev-act
      #
      #   - /^master(-patch.*)?$/
      #   - /^develop(-patch.*)?$/
      #   - master
      #   - develop
      # #remove after upgrade
      #   - angular-14-rebase
      #   - /.*old-env.*/
      #   - /.*next-release.*/
      #   - /.*beta.*/
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: Enable SSH debug
        type: boolean
        required: false
        default: false
    ssh_debug_timeout:
      debug_enabled:
        description: SSH debug timeout, in minutes
        required: false
        default: "60"

# on:
#   pull_request:
#     types:
#       - closed

# jobs:
#   if_merged:
#     if: github.event.pull_request.merged == true
#     runs-on: ubuntu-latest
#     steps:
#     - run: |
#         echo The PR was merged

# on:
#   pull_request:
#     types: [opened, reopened]
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
env:
  TRAVIS_BRANCH: ${{ github.ref_name }}
  GITHUB_BRANCH: ${{ github.ref_name }}
  TRAVIS_BUILD_DIR: ${{ github.workspace }}
  TRAVIS_COMMIT: ${{ github.sha }}
  TRAVIS_BUILD_ID: ${{ github.run_id }}
  TRAVIS_RUN_NUMBER: ${{ github.run_attempt }}
  E2E_HOST: ${{ secrets.E2E_HOST }}
  E2E_USERNAME: ${{ secrets.E2E_USERNAME }}
  E2E_PASSWORD: ${{ secrets.E2E_PASSWORD }}
  AWS_S3_BUCKET_ACTIVITI_LICENSE: ${{ secrets.AWS_S3_BUCKET_ACTIVITI_LICENSE }}
  HOST_SSO: ${{ secrets.HOST_SSO }}
jobs:
  main:
    timeout-minutes: 80
    name: "Build Components"
    runs-on: ubuntu-22.04
    # TODO : pull request not merged
    # if: github.event.pull_request.merged == true
    env:
      TRAVIS_BRANCH: develop
      # TRAVIS_EVENT_TYPE: push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches
      - uses: ./.github/actions/setup
      - name: debug nx-set-sha
        run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"
      - name: override NX_CALCULATION_FLAGS
        run: echo 'NX_CALCULATION_FLAGS=--base=origin/develop --head=HEAD' >> $GITHUB_ENV
      - run: echo $TRAVIS_EVENT_TYPE
      - run: echo $S3_NODE_MODULES_CACHE_ID
      - run: echo $HEAD_COMMIT_HASH
      - run: echo $NX_CALCULATION_FLAGS
      # TODO TRAVIS_JOB_ID TO SET
      - run: npm ci
      - run: npx nx affected $NX_CALCULATION_FLAGS --target=lint --parallel=3
      - name: install chrome
        uses: browser-actions/setup-chrome@latest
      - name: install xvfb
        run: sudo apt-get install -y x11-xserver-utils xvfb
      - run: /usr/bin/xvfb-run --auto-servernum npx nx affected:test $NX_CALCULATION_FLAGS --exclude="insights,core,extensions,process-services,process-services-cloud" }}
      - name: test cleanup
        run: |
          xvfb_pid=$(ps x | grep -v grep | grep xvfb-run | awk '{print $1}')
          if [ "$xvfb_pid" != "" ]; then
              echo "Killing the following xvfb process: $xvfb_pid"
              sudo kill $xvfb_pid
          else
              echo "Nothing to kill"
          fi
      - run: nx affected:build $NX_CALCULATION_FLAGS --prod --exclude="demoshell"
      - run: nx $NX_CALCULATION_FLAGS build demoshell --configuration production
      - run: nx build demoshell --configuration production
      - run: nx run stories:build-storybook --configuration ci
      - run: nx run testing:bundle
      # UPDATE BUILD CACHE

      - name: Install playRight
        run: |
          npm install -D @playwright/test
          npx playwright install
      - name: build adf cli
        run: |
          nx build cli
      - name: Process Cloud Storybook Playwright
        # if: matrix.components == 'process Cloud::Storybook Playwright'
        run: |
          npx playwright install chromium
          sudo sysctl -w fs.inotify.max_user_watches=524288
          npx playwright test --config='e2e-playwright/playwright.config.ts' || exit 1
      - name: debug
        run: ls -lath node_modules/@alfresco || true
      - uses: ./.github/actions/upload-artifacts  
      - name: copy cli into node modules
        run: nx run cli:bundle
        shell: bash
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      #   with:
      #     timeout-minutes: ${{ inputs.ssh_debug_timeout }}
      #     limit-access-to-actor: true
      # - run: sleep 300
      #   if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      - name: e2e
        uses: ./.github/actions/e2e
        with:
          test-id: core
          upload-to-s3: false
          download-from-s3: false

  get-artifacts:
    timeout-minutes: 80
    name: "get artifacts"
    needs: [ main ]
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/download-artifacts
      - run: ls -lh | grep nxcache
      - run: ls -lh | grep dist
