name: pr-workflow

on:
  workflow_call:
    inputs:
      dry-run-release:
        description: 'enable dry-run'
        required: false
        type: boolean
        default: true
      devel:
        description: 'enable pipeline devel'
        required: false
        type: boolean
        default: true
  push:
    branches:
      - "AAE-12860*"


jobs:
  general-build:
    uses: ./.github/workflows/pull-request.yml
    secrets: inherit
    with:
      devel: true
