name: "devel mau"

on:
  workflow_call:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
      - master
      - develop-patch*
      - master-patch*

jobs:

  check-if-pr-is-approved:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get branch name
        uses: Alfresco/alfresco-build-tools/.github/actions/get-branch-name@v1.36.0

       - name: Get PR number
        uses: Alfresco/alfresco-build-tools/.github/actions/get-pr-number@v1.36.0
        with:
          branch-name: $BRANCH_NAME
