name: "git-tag"

on:
  workflow_call:
    inputs:
      dry-run-flag:
        description: 'enable dry-run on artifact push'
        required: false
        type: boolean
        default: true

  push:
    branches:
      - master
      - master-patch-*

env:
  BASE_REF: ${{ github.base_ref }}
  HEAD_REF: ${{ github.head_ref }}
  GH_COMMIT: ${{ github.sha }}
  GH_BUILD_NUMBER: ${{ github.run_id }}
  LOG_LEVEL: "ERROR"
  NODE_OPTIONS: "--max-old-space-size=5120"
  NPM_REGISTRY_ADDRESS: ${{ secrets.NPM_REGISTRY_ADDRESS }}
  BOT_GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}

jobs:

  release:
    uses: ./.github/workflows/release.yml
    secrets: inherit
    with:
      dry-run-flag: false

  setup:
    needs: release
    timeout-minutes: 20
    name: "Release tag"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: $BOT_GITHUB_TOKEN
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - id: set-dryrun
        uses: ./.github/actions/enable-dryrun
        with:
          dry-run-flag: ${{ inputs.dry-run-flag }}
      - name: install NPM
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: '.nvmrc'
      - name: "Release tag"
        env:
          DRYRUN_FLAG: ${{ steps.set-dryrun.outputs.dryrun }}
        run: |
          git fetch --all --quiet
          BRANCH=${GITHUB_REF##*/} ./scripts/github/release/git-tag.sh $DRYRUN_FLAG
