name: Package published
on:
  registry_package:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch event to monorepo
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            echo ${{ toJSON(github.event) }}
            const payload = {
              package_name: github.event.package.name,
              package_version: github.event.package.version
            };

            const octokit = new Octokit();
            await octokit.repos.createDispatchEvent({
              owner: 'Alfresco',
              repo: 'alfresco-apps',
              event_type: 'package-published',
              client_payload: payload
            });

