name: Package published
on:
  registry_package:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch event to monorepo
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const payload = {
              package_name: github.event.registry_package.name,
              package_version: github.event.package_version.name
              package_commit_sha: github.event.package_version.target_oid
            };

            await github.repos.createDispatchEvent({
              owner: 'Alfresco',
              repo: 'alfresco-apps',
              event_type: 'package-published',
              client_payload: payload
            });

            console.log(`Trigger a dispatch event for the monorepo`);
