name: "pull-request"

on:
  workflow_call:
    inputs:
      dry-run-flag:
        description: 'enable dry-run on artifact push'
        required: false
        type: boolean
        default: true
      devel:
        description: 'devel'
        required: false
        type: boolean
        default: false
      cron-run:
        description: 'disables jobs which should not run when cron runs e2es'
        required: false
        type: boolean
        default: false
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
      - master
      - develop-patch*
      - master-patch*

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

env:
  BASE_REF: "${{ github.base_ref }}"
  HEAD_REF: "${{ github.head_ref }}"
  AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
  GITHUB_BRANCH: "${{ github.ref_name }}"
  GH_BUILD_DIR: "${{ github.workspace }}"
  GH_COMMIT: "${{ github.sha }}"
  BUILD_ID: "${{ github.run_id }}"
  GH_RUN_NUMBER: "${{ github.run_attempt }}"
  GH_BUILD_NUMBER: "${{ github.run_id }}"
  JOB_ID: "${{ github.run_id }}"
  LOG_LEVEL: "ERROR"
  S3_BUILD_BUCKET_SHORT_NAME: "${{ secrets.S3_BUILD_BUCKET_SHORT_NAME }}"
  NODE_OPTIONS: "--max-old-space-size=5120"
  DOCKER_REPOSITORY_DOMAIN: "${{ secrets.DOCKER_REPOSITORY_DOMAIN }}"
  DOCKER_REPOSITORY_USER: "${{ secrets.DOCKER_REPOSITORY_USER }}"
  DOCKER_REPOSITORY_PASSWORD: "${{ secrets.DOCKER_REPOSITORY_PASSWORD }}"
  DOCKER_REPOSITORY_STORYBOOK: "${{ secrets.DOCKER_REPOSITORY_DOMAIN }}/alfresco/storybook"
  REPO_OWNER: "Alfresco"
  REPO_NAME: "alfresco-ng2-components"
  STORYBOOK_DIR: "./dist/storybook/stories"
  BUILT_LIBS_DIR: "./dist/libs"
  NODE_MODULES_DIR: "./node_modules"
  REDIRECT_URI: "/"

jobs:
  pre-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0

      - name: Ensure SHA pinned actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@25ed13d0628a1601b4b44048e63cc4328ed03633

      - name: Check package-lock.json version
        run: |
          if [[ $(jq '.lockfileVersion == 3' package-lock.json) == "true" ]] ; then
            echo "package-lock.json has a correct version"
          else
            echo "package-lock must be version 3"
            exit 1
          fi

  check-if-pr-is-approved:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
      - name: Get branch name
        uses: Alfresco/alfresco-build-tools/.github/actions/get-branch-name@c1236aee36bb9b35c5972819fcf8a4d07572e6cd
      - name: Save commit message
        uses: Alfresco/alfresco-build-tools/.github/actions/get-commit-message@c1236aee36bb9b35c5972819fcf8a4d07572e6cd
      - name: ci:force flag parser
        shell: bash
        run: |
          if [ "${{ github.event_name }}" == "schedule" ] || [ "${{ github.actor }}" == "dependabot[bot]" ]; then
            echo "ci:force check can be skipped"
            skip_check="true"
          elif [[ "$COMMIT_MESSAGE" == *"[ci:force]"* ]]; then
              echo "[ci:force] flag detected. No need for approval."
              skip_check="true"
          fi
      - name: Get PR number
        if: ${{ github.event_name != 'schedule' && github.event_name != 'workflow_dispatch' }}
        uses: kamatama41/get-pr-number-action@0bcaab5752c0b699149e74667c8ce2f764cbb7fa
        id: action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Show PR number
        shell: bash
        run: echo "PR: ${{ steps.action.outputs.number }}"
      - name: Check if PR is approved
        env:
          DEVEL_FLAG: "${{ inputs.devel }}"
          GH_TOKEN: "${{ github.token }}"
        run: |
          if [ "${{ github.event_name }}" == "schedule" ] || [ "${{ github.actor }}" == "dependabot[bot]" ]; then
            echo "ci:force check can be skipped"
            exit 0
          fi
          if [[ "$COMMIT_MESSAGE" == *"[ci:force]"* ]]; then
            echo "[ci:force] flag detected. No need for approval."
            exit 0
          fi
          if [ "${{ github.actor }}" == "dependabot[bot]" ] || [ "${{ github.actor }}" == "alfresco-build" ]; then
            echo "Commit by ${{ github.actor }}. No need for approval."
            exit 0
          fi
          if [ "${{ github.event_name }}" == "schedule" ] || [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "Schedule event"
            exit 0
          fi
          if [[ "$DEVEL_FLAG" == "true" ]]; then
            echo "Devel flag"
            exit 0
          fi
          prNumber=${{ steps.action.outputs.number }}
          echo "Checking PR approval for PR $prNumber"
          checkApproval=$(gh api /repos/${{ github.repository }}/pulls/$prNumber/reviews | jq '.[].state' | grep APPROVED)
          if [ -n "$checkApproval" ]; then
            echo "PR approved"
          else
            echo "PR NOT approved"
            exit 1
          fi

  setup:
    timeout-minutes: 30
    name: "Setup"
    runs-on: ubuntu-latest
    needs: [check-if-pr-is-approved, pre-checks]
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - name: Install dependencies
        run: |
          npm ci
          npx nx run js-api:bundle
          npx nx run cli:bundle
      - uses: ./.github/actions/upload-node-modules-and-artifacts

  unit-tests:
    timeout-minutes: 30
    name: "Unit tests: ${{ matrix.unit-tests.name }}"
    runs-on: ubuntu-latest
    needs: [setup]
    strategy:
      fail-fast: false
      matrix:
        unit-tests:
          - name: "js-api"
            exclude: "core,insights,content-services,process-services,process-services-cloud,eslint-plugin-eslint-angular"
          - name: "content-services"
            exclude: "insights,core,extensions,process-services,process-services-cloud,eslint-plugin-eslint-angular,js-api"
          - name: "core"
            exclude: "insights,extensions,content-services,process-services,process-services-cloud,eslint-plugin-eslint-angular,js-api"
          - name: "insights"
            exclude: "core,extensions,content-services,process-services-cloud,process-services,eslint-plugin-eslint-angular,js-api"
          - name: "process-services"
            exclude: "core,extensions,content-services,process-services-cloud,insights,eslint-plugin-eslint-angular,js-api"
          - name: "process-cloud"
            exclude: "insights,core,extensions,content-services,process-services,eslint-plugin-eslint-angular,js-api"
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/download-node-modules-and-artifacts
      - name: Run unit tests
        env:
          NODE_OPTIONS: "--max-old-space-size=5120"
        run: |
          echo "Running unit tests (excluding: ${{ matrix.unit-tests.exclude }})"
          xvfb-run --auto-servernum npx nx affected:test --exclude="${{ matrix.unit-tests.exclude }}" --verbose

  lint:
    timeout-minutes: 30
    name: "Lint"
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/download-node-modules-and-artifacts
      - run: npx nx affected --target=lint $NX_CALCULATION_FLAGS

  build-libs:
    timeout-minutes: 30
    name: "Build libs"
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/download-node-modules-and-artifacts
      - run: |
          NX_REJECT_UNKNOWN_LOCAL_CACHE=0 npx nx affected:build $NX_CALCULATION_FLAGS --prod
          NX_REJECT_UNKNOWN_LOCAL_CACHE=0 npx nx affected --target=build-storybook $NX_CALCULATION_FLAGS --configuration=ci
      - uses: ./.github/actions/upload-node-modules-and-artifacts

  PR-forbidden-labels:
    if: ${{ inputs.cron-run == '' || inputs.cron-run == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - id: checkoutRepo
        name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 1
      - name: PR contains forbidden labels
        id: pr-forbidden
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
        with:
          script: |
            const issueHasLabels = require('./scripts/github/update/check-issue-has-label.js');
            const checkLabels = ['next version ➡️', 'do not merge🙅🏻‍♂️'];
            const hasLabel = await issueHasLabels({github, context, checkLabels});
            if (hasLabel) {
              core.setFailed('The PR contains a forbidden label! You are not allowed to merge until the label is removed.');
            }
      - name: Check value after
        run: |
          echo "result: ${{ toJson(steps.pr-forbidden.result) }}"

  finalize:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Final Results
    needs: [check-if-pr-is-approved, pre-checks, setup, unit-tests, lint, build-libs]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Identify Slack group
        id: groups
        if: ${{ github.event_name == 'schedule' }}
        uses: ./.github/actions/slack-group-area
        with:
          affected: ${{ steps.e2e-result.outputs.result }}
      - uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d
        name: Notify QA failure
        if: ${{ github.event_name == 'schedule' && contains(needs.*.result, 'failure') }}
        env:
          SLACK_BOT_TOKEN: "${{ secrets.SLACK_BOT_TOKEN }}"
        with:
          channel-id: 'C016SMNNL8L'
          slack-message: |
            🔴 Warning: The daily ADF cronjob failed
            Workflow run: <https://github.com/Alfresco/alfresco-ng2-components/actions/runs/${{ github.run_id }}| here>
            Details: ${{ steps.e2e-result.outputs.result }}
            Area: ${{ steps.groups.outputs.groups }}
      - name: Workflow failure
        run: exit 1
        if: ${{ contains(needs.*.result, 'failure') }}
      - name: Workflow canceled
        run: exit 1
        if: ${{ contains(needs.*.result, 'cancelled') }}
      - name: Workflow success
        run: exit 0
        if: ${{ contains(needs.*.result, 'success') }}
