name: "pull-request"

on:
  workflow_call:
    inputs:
      dry-run-flag:
        description: "enable dry-run on artifact push"
        required: false
        type: boolean
        default: true
      devel:
        description: "devel"
        required: false
        type: boolean
        default: false
      cron-run:
        description: "disables jobs which should not run when cron runs e2es"
        required: false
        type: boolean
        default: false
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
      - master
      - develop-patch*
      - master-patch*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BASE_REF: ${{ github.base_ref }}
  HEAD_REF: ${{ github.head_ref }}
  GH_COMMIT: ${{ github.sha }}
  GH_BUILD_NUMBER: ${{ github.run_id }}
  LOG_LEVEL: "ERROR"
  NODE_OPTIONS: "--max-old-space-size=5120"

jobs:
  pre-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Ensure SHA pinned actions
        uses: hyland/github-actions-ensure-sha-pinned-actions@7d494b6b53e71f75194d74b4dd890a2266d060b5 # v2.0.0

      - name: Check package-lock.json version
        run: |
          if [[ $(jq '.lockfileVersion == 3' package-lock.json) == "true" ]] ; then
            echo "package-lock.json has a correct version"
          else
            echo "package-lock must be version 3"
            exit 1
          fi

  check-if-pr-is-approved:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Get branch name
        uses: Alfresco/alfresco-build-tools/.github/actions/get-branch-name@f95467b62527ce087c9a1b7e55c467061cf827a0 # v17.6.1

      - name: Save commit message
        uses: Alfresco/alfresco-build-tools/.github/actions/get-commit-message@f95467b62527ce087c9a1b7e55c467061cf827a0 # v17.6.1
        with:
          header-only: true

      - name: ci:force flag parser
        shell: bash
        env:
          EVENT_NAME: ${{ github.event_name }}
          ACTOR: ${{ github.actor }}
        run: |
          if [ "$EVENT_NAME" == "schedule" ] || [ "$ACTOR" == "dependabot[bot]" ]; then
            echo -e "\033[32mci:force check can be skipped\033[0m"
            skip_check="true"
          elif [[ "$COMMIT_MESSAGE" == *"[ci:force]"* ]]; then
              echo -e "\033[32m[ci:force] flag detected. No need for approval.\033[0m"
              skip_check="true"
          fi

      - name: Get PR number
        if: ${{ github.event_name != 'schedule' && github.event_name != 'workflow_dispatch' }}
        uses: kamatama41/get-pr-number-action@ff143e03abaa79d346ca5407d49d335b5def979e # v1.0.1
        id: action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: show pr number
        shell: bash
        env:
          PR_NUMBER: ${{ steps.action.outputs.number }}
        run: |
          echo "PR: $PR_NUMBER"

      - name: check if pr is approved
        env:
          DEVEL_FLAG: ${{ inputs.devel }}
          GH_TOKEN: ${{ github.token }}
          skip_check: "false"
          EVENT_NAME: ${{ github.event_name }}
          ACTOR: ${{ github.actor }}
          PR_NUMBER: ${{ steps.action.outputs.number }}
        run: |
          if [ "$EVENT_NAME" == "schedule" ] || [ "$ACTOR" == "dependabot[bot]" ]; then
            echo -e "\033[32mci:force check can be skipped\033[0m"
            skip_check="true"
          elif [[ "$COMMIT_MESSAGE" == *"[ci:force]"* ]]; then
            echo -e "\033[32m[ci:force] flag detected. No need for approval.\033[0m"
            skip_check="true"
          fi

          if [ "$ACTOR" == "dependabot[bot]" ] || [ "$ACTOR" == "alfresco-build" ]; then
            echo -e "\033[32mCommit by $ACTOR. No need for approval.\033[0m"
            skip_check="true"
          fi
          if [ "$EVENT_NAME" == "schedule" ] || [ "$EVENT_NAME" == "workflow_dispatch" ]; then
            echo -e "\033[32mSchedule event\033[0m"
            skip_check="true"
          fi

          if [[ "$DEVEL_FLAG" == "true" ]]; then
            echo -e "\033[32mDevel flag\033[0m"
            skip_check="true"
          fi

          if [ "$skip_check" == "false" ]; then
            echo "Checking PR approval"
            prNumber=$PR_NUMBER
            echo "PR: $prNumber"
            checkApproval=$(gh api /repos/$GITHUB_REPOSITORY/pulls/$prNumber/reviews | jq '.[] | select(.state == "APPROVED") | .user.login')
            if [[ $checkApproval ]]; then
              echo -e "\033[32mPR approved\033[0m"
            else
              echo -e "\033[31mPR NOT approved\033[0m"
              exit 1
            fi
          fi

  setup:
    timeout-minutes: 30
    name: "Setup"
    runs-on: ubuntu-latest
    needs: [check-if-pr-is-approved, pre-checks]
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Setup environment
        id: setup-env
        uses: ./.github/actions/setup
      - name: Install dependencies
        if: ${{ steps.setup-env.outputs.node-modules-cache-hit != 'true' }}
        run: npm ci
      - name: Bundle
        run: |
          npm run bundle:js-api
          npm run bundle:cli

  lint:
    timeout-minutes: 30
    name: "Lint"
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Setup environment
        id: setup-env
        uses: ./.github/actions/setup
      - name: Install dependencies
        if: ${{ steps.setup-env.outputs.node-modules-cache-hit != 'true' }}
        run: npm ci
      - run: npx nx affected --target=lint --base=origin/${{ github.event.pull_request.base.ref }} --head=HEAD

  trigger-build:
    name: "Build Libs"
    needs: [setup]
    uses: ./.github/workflows/build-lib-workflow.yml

  build-storybook:
    timeout-minutes: 30
    name: "Build Storybook"
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Setup environment
        id: setup-env
        uses: ./.github/actions/setup
      - name: Install dependencies
        if: ${{ steps.setup-env.outputs.node-modules-cache-hit != 'true' }}
        run: npm ci
      - name: Build Storybook
        run: |
          NX_REJECT_UNKNOWN_LOCAL_CACHE=0 npx nx affected --target=build-storybook --base=origin/${{ github.event.pull_request.base.ref }} --head=HEAD --configuration=ci

  trigger-unit-tests:
    name: "Unit Tests"
    needs: [setup]
    uses: ./.github/workflows/unit-test-workflow.yml

  PR-forbidden-labels:
    if: ${{ inputs.cron-run == '' || inputs.cron-run == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - id: checkoutRepo
        name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1
      - name: PR contains forbidden labels
        id: pr-forbidden
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const issueHasLabels = require('./scripts/github/update/check-issue-has-label.js');
            const checkLabels = ['next version ➡️', 'do not merge🙅🏻‍♂️'];

            const hasLabel = await issueHasLabels({github, context, checkLabels})

            if(hasLabel) {
              core.setFailed('The PR contains a forbidden label! You are not allowed to merge until the label is there.');
            }

  finalize:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Final Results
    needs:
      [
        check-if-pr-is-approved,
        pre-checks,
        trigger-unit-tests,
        lint,
        trigger-build,
        build-storybook,
        PR-forbidden-labels,
      ]
    steps:
      - name: Check job execution status
        if: >-
          ${{
              contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
          }}
        run: exit 1
