name: Pull Translations from Crowdin
on:
  schedule:
    - cron: "0 7-17 * * 1-5"
  workflow_dispatch:
  workflow_call:
    secrets:
      GH_APP_ENGINEERING_CONTRIB_PRIVATE_KEY:
        required: true
      CROWDIN_TRANSLATIONS_TOKEN:
        required: true
      HXPS_GIT_COMMIT_SIGNING_PRIVATE_KEY:
        required: true
jobs:
  pull-from-crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Generate app token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.GH_APP_ENGINEERING_CONTRIB_CLIENT_ID }}
          private-key: ${{ secrets.GH_APP_ENGINEERING_CONTRIB_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: develop
          token: ${{ steps.app-token.outputs.token }}
      - name: Pull translations from Crowdin
        uses: crowdin/github-action@c7af9bc98b01694653031fef2a0dc6c7888ce9bc # v2.17.0
        with:
          skip_ref_checkout: true
          upload_sources: false
          download_translations: true
          create_pull_request: true
          localization_branch_name: automated-translations-update
          pull_request_title: "GH auto: Automated Update of Translations from Crowdin"
          pull_request_base_branch_name: develop
          github_user_name: ${{ vars.HXPS_GIT_USERNAME }}
          github_user_email: ${{ vars.HXPS_GIT_EMAIL }}
          gpg_private_key: ${{ secrets.HXPS_GIT_COMMIT_SIGNING_PRIVATE_KEY }}
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          CROWDIN_TOKEN: ${{ secrets.CROWDIN_TRANSLATIONS_TOKEN }}
