name: Pull Translations from Crowdin
on:
  schedule:
    - cron: "0 7-17 * * 1-5"
  workflow_dispatch:
jobs:
  pull-from-crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Pull translations from Crowdin
        uses: crowdin/github-action@08713f00a50548bfe39b37e8f44afb53e7a802d4 # v2.12.0
        with:
          upload_sources: false
          download_translations: true
          create_pull_request: true
          localization_branch_name: automated-translations-update
          pull_request_title: "GH auto: Automated Update of Translations from Crowdin"
          pull_request_base_branch_name: develop
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          CROWDIN_TOKEN: ${{ secrets.CROWDIN_TRANSLATIONS_TOKEN }}
