name: "release"

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'enable dry-run on artifact push'
        required: false
        type: boolean
        default: false

permissions:
  id-token: write # Required for OIDC
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  LOG_LEVEL: "ERROR"
  NODE_OPTIONS: "--max-old-space-size=5120"

jobs:
  release-npm:
    timeout-minutes: 45
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: install
        run: npm ci

      - name: build libraries
        run: |
          npm run build:libs
          npm run build:schematics

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        name: release libraries Npm registry
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://${{ vars.NPM_REGISTRY_ADDRESS }}'
          scope: '@alfresco'

      - name: upgrade npm
        run: |
          npm install -g npm@11
          npm --version

      - run: npx nx run-many -t npm-publish --tag=branch ${{ inputs.dry-run && '--dry-run' || '' }}
