name: "release"

on:
  workflow_call:
    inputs:
      dry-run-flag:
        description: 'enable dry-run on artifact push'
        required: false
        type: boolean
        default: true
  workflow_dispatch:
    inputs:
      dry-run-flag:
        description: 'enable dry-run on artifact push'
        required: false
        type: boolean
        default: true
  pull_request:
    types: [closed]
    branches:
      - develop
      - master
      - develop-patch*
      - master-patch*

permissions:
  id-token: write  # Required for OIDC
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  BASE_REF: ${{ github.base_ref }}
  HEAD_REF: ${{ github.head_ref }}
  GH_COMMIT: ${{ github.sha }}
  GH_BUILD_NUMBER: ${{ github.run_id }}
  LOG_LEVEL: "ERROR"
  NODE_OPTIONS: "--max-old-space-size=5120"

jobs:
  setup:
    timeout-minutes: 20
    if: github.event.pull_request.merged == true || github.ref_name == 'master' || github.ref_name == 'master-patch-*' || github.event_name == 'workflow_dispatch'
    name: "Setup"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
        with:
          enable-node-modules-cache: false
      - name: install
        run: |
          npm ci
          npx nx run js-api:bundle
          npx nx run cli:bundle

  release-npm:
    needs: [setup]
    outputs:
      release_version: ${{ steps.set-version.outputs.release_version }}
    timeout-minutes: 30
    if: github.event.pull_request.merged == true || github.ref_name == 'master' || github.ref_name == 'master-patch-*' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - id: setup
        uses: ./.github/actions/setup
        with:
          enable-node-modules-cache: false
      - id: set-dryrun
        uses: ./.github/actions/enable-dryrun
        with:
          dry-run-flag: ${{ inputs.dry-run-flag }}
      - name: Set libraries versions
        id: set-version
        run: |
          set -u;
          ./scripts/github/build/bumpversion.sh
      - name: build libraries
        run: |
          npx nx run-many -t build --prod --skip-nx-cache
          npx nx run-many -t build-schematics
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        name: release libraries GH registry
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@alfresco'
      - run: npx nx run-many -t npm-publish --tag=${{ steps.setup.outputs.npm-tag }} || exit 1
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        name: release libraries Npm registry
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://${{ vars.NPM_REGISTRY_ADDRESS }}'
          scope: '@alfresco'
      - run: npx nx run-many -t npm-publish --tag=${{ steps.setup.outputs.npm-tag }} || exit 1

  create-git-tag:
    runs-on: ubuntu-latest
    needs: [setup, release-npm]
    if: github.event_name != 'workflow_dispatch'
    name: Create github tag
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1
      - uses: './.github/actions/create-git-tag'
        with:
          tagName: ${{ needs.release-npm.outputs.release_version }}

  npm-check-bundle:
    needs: [release-npm]
    timeout-minutes: 15
    if: github.event.pull_request.merged == true || github.ref_name == 'master' || github.ref_name == 'master-patch-*' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/npm-check-bundle

  finalize:
    if: always()
    runs-on: ubuntu-latest
    name: Final Results
    needs: [release-npm, npm-check-bundle]
    steps:
      - name: Check job execution status
        if: >-
          ${{
              contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
          }}
        run: exit 1
