name: "SonarCloud Full Scan (develop)"

on:
  push:
    branches:
      - develop
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  full-unit-tests-and-sonar-scan:
    name: "Full Unit Tests + SonarCloud Scan"
    uses: ./.github/workflows/unit-test-workflow.yml
    secrets: inherit
    with:
      full: true
