name: "Unit Tests Workflow"

on:
  workflow_call: {}

jobs:
  generate-affected-matrix:
    name: "Generate affected matrix"
    runs-on: ubuntu-latest
    outputs:
      unitMatrix: ${{ steps.set-matrix.outputs.unitMatrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
      - name: Setup environment
        uses: ./.github/actions/setup
      - name: Install dependencies
        run: npm ci
      - name: Generate affected projects matrix
        id: set-matrix
        run: |
          BASE_REF="${{ github.event.pull_request.base.ref }}"
          echo "Base ref is $BASE_REF"
          AFFECTED_UNIT=$(npx nx show projects --affected --target=test --base=origin/$BASE_REF --select=projects --plain --exclude=cli,stories,eslint-angular)
          echo "Affected projects for UNIT : $AFFECTED_UNIT"
          UNIT_MATRIX_JSON=$(echo $AFFECTED_UNIT | xargs -n1 | jq -R -s -c 'split("\n")[:-1] | map({ "project": . })')
          UNIT_MATRIX_JSON=$(echo "$UNIT_MATRIX_JSON" | tr -d '\n' | sed 's/"$//')
          echo "Matrix UNIT: $UNIT_MATRIX_JSON"
          echo "unitMatrix=$UNIT_MATRIX_JSON" >> $GITHUB_OUTPUT

  unit-tests:
    runs-on: ubuntu-latest
    needs: generate-affected-matrix
    strategy:
      matrix:
        include: ${{ fromJson(needs.generate-affected-matrix.outputs.unitMatrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
      - name: Setup environment
        uses: ./.github/actions/setup
      - name: Run unit tests for ${{ matrix.project }}
        env:
          NODE_OPTIONS: "--max-old-space-size=5120"
        run: |
          xvfb-run --auto-servernum npx nx run ${{ matrix.project }}:test
